name: MLOps Pipeline - Clase 3

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  train-test:
    runs-on: ubuntu-latest

    steps:
      - name: 1) Clonar repositorio
        uses: actions/checkout@v4

      - name: 2) Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 3) Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 4) Entrenar el modelo
        run: python train.py

      - name: 5) Evaluar modelo y generar métricas
        run: python test.py

      - name: 6) Publicar métricas y gráfica
        uses: actions/upload-artifact@v4
        with:
          name: resultados
          path: |
            metrics.txt
            resultados.png

