name: MLOps Pipeline - Clase 3

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  train-test:
    runs-on: ubuntu-latest

    steps:
      - name: 1) Clonar repositorio
        uses: actions/checkout@v3

      - name: 2) Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 3) Instalar dependencias
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: 4) Entrenar modelo
        run: python train.py

      - name: 5) Evaluar modelo
        run: python test.py

      - name: 6) Publicar métricas y gráfica
        uses: actions/upload-artifact@v3
        with:
          name: resultados
          path: |
            metrics.txt
            resultados.png
